[build]
  command = "npm run build && mkdir -p public/secrets && openssl enc -aes-256-cbc -d -salt -in secrets/google-cloud-key.enc -out public/secrets/google-cloud-key.json -k $GOOGLE_CLOUD_FILE_ENCRYPTION_KEY"
