import "./globals.css";
import { Inter } from "next/font/google";

import AuthProvider from "@/context/AuthProvider";

import DrawerAppBar from "@/components/Appbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJS Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <DrawerAppBar />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
