name: MongoDB Backup

on:
  schedule:
    - cron: "0 3 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install MongoDB Tools
        run: |
          wget -qO- https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-100.9.4.tgz | tar -xz
          sudo mv mongodb-database-tools-*/bin/* /usr/local/bin/

      - name: Run MongoDB Backup
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          mongodump --uri="$MONGO_URL" --archive=backup_$TIMESTAMP.gz --gzip
          mv backup_$TIMESTAMP.gz backup.gz

      - name: Upload to Google Cloud Storage
        env:
          GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          GOOGLE_CLOUD_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLOUD_CLIENT_EMAIL }}
          GOOGLE_CLOUD_PRIVATE_KEY: ${{ secrets.GOOGLE_CLOUD_PRIVATE_KEY }}
        run: |
          echo '{
            "type": "service_account",
            "project_id": "'"$GOOGLE_CLOUD_PROJECT_ID"'",
            "client_email": "'"$GOOGLE_CLOUD_CLIENT_EMAIL"'",
            "private_key": "'"$GOOGLE_CLOUD_PRIVATE_KEY"'"
          }' > gcs-key.json
          gcloud auth activate-service-account --key-file=gcs-key.json
          gsutil cp backup.gz gs://$GCS_BUCKET/mongo_$TIMESTAMP.gz
